export const ROLES = {
    ADMIN: "ADMIN",
    USER: "USER",
} as const;

export const PERMISSIONS = {
    FLOW_BUILDER: "FLOW_BUILDER",
    MANAGE_USERS: "MANAGE_USERS",
    MANAGE_CLIENTS: "MANAGE_CLIENTS",
    MANAGE_MULTIBOT: "MANAGE_MULTIBOT",
    ANALYTICS: "ANALYTICS",
    MANAGE_SETTINGS: "MANAGE_SETTINGS",
} as const;
